apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
spec:
  template:
    metadata:
      name: helloworld-00002-qef
    spec:
      containerConcurrency: 80
      containers:
        - image: gcr.io/my-cloud-run-test-project/helloworld
          ports:
            - containerPort: ${PORT:-3000}
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
