name: PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  doit:
    if: contains(github.event.comment.body, 'test')
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo ${{ toJson(github.event) }}
