name: PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  doit:
    if: contains(github.event.issue.body, "test")
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "${{ github.event.issue.body }}!!!!!!!!!!!!!!!"
