name: Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        dirs: [service-one, service-two]

    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     ref: origin/${{ github.base_ref }}

      - uses: actions/checkout@v2
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*


        # with:
        #   fetch-depth: 0
      - name: Check Git Diff Log
        # run: git diff --name-only --quiet ${{ github.sha }} ${{ github.base_ref }} ${{ matrix.dirs }}
        run: git diff --name-only --quiet origin/${{ github.base_ref }} ${{ github.head_ref }} ${{ matrix.dirs }}

      - name: Check Git Diff
        id: git-check
        run: echo ::set-output name=changed::$(if git diff --name-only --quiet ${{ github.sha }} ${{ github.base_ref }} ${{ matrix.dirs }}; then echo "false"; else echo "true"; fi)

      - name: Do something
        if: steps.git-check.outputs.changed == 'true'
        run: echo "YEP CHANGED!"
