name: My Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: My Test
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
        run: git diff --name-only HEAD HEAD~1
