name: My Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        dirs: [service-one, service-two]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: My Test
        if: git diff --name-only HEAD HEAD~1 ${{ matrix.dirs }}
        # run: git diff --name-only HEAD HEAD~1 ${{ matrix.dirs }}
        run: echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
